name: mess_mate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  firebase_auth: ^5.3.4
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter:
    sdk: flutter
  flutter_custom_tabs: ^2.1.0
  flutter_expanded_tile: ^0.4.0
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^10.8.0
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  intl: ^0.20.1
  pie_chart: ^5.4.0
  provider: ^6.1.2
  stylish_bottom_bar: ^1.1.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
